package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1



/**
 * Admins generated by hbm2java
 */
public class Admins  implements java.io.Serializable {


     private String email;
     private String password;
     private Boolean loggedin;
     private String role;

    public Admins() {
    }

	
    public Admins(String email, String role) {
        this.email = email;
        this.role = role;
    }
    public Admins(String email, String password, Boolean loggedin, String role) {
       this.email = email;
       this.password = password;
       this.loggedin = loggedin;
       this.role = role;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getLoggedin() {
        return this.loggedin;
    }
    
    public void setLoggedin(Boolean loggedin) {
        this.loggedin = loggedin;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


