package Mapping.POJO;
// Generated Mar 7, 2015 9:53:12 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String email;
     private String password;
     private Boolean loggedin;

    public Admin() {
    }

	
    public Admin(String email) {
        this.email = email;
    }
    public Admin(String email, String password, Boolean loggedin) {
       this.email = email;
       this.password = password;
       this.loggedin = loggedin;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getLoggedin() {
        return this.loggedin;
    }
    
    public void setLoggedin(Boolean loggedin) {
        this.loggedin = loggedin;
    }




}


