package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1

/**
 * Courses generated by hbm2java
 */
public class Courses implements java.io.Serializable {

    private int courseid;
    private int schoolid;
    private String coursename;
    private String description;
    private String courseidentifier;
    private Integer numstudents;
    private String instructor;
    private int scheduleblockid;
    private String semester;
    private String friends;

    public String getFriends() {
        return friends;
    }

    public void setFriends(String friends) {
        this.friends = friends;
    }

    public String getSemester() {
        return semester;
    }

    public void setSemester(String semester) {
        this.semester = semester;
    }

    public Courses() {
    }

    public Courses(int schoolid, String coursename, String courseidentifier, String instructor, int scheduleblockid, String semester){
        this.schoolid = schoolid;
        this.coursename = coursename;
        this.courseidentifier = courseidentifier;
        this.instructor = instructor;
        this.scheduleblockid = scheduleblockid;
        this.semester = semester;
    }
    public Courses(int schoolid, String coursename, String courseidentifier, String instructor, int scheduleblockid){
        this.schoolid = schoolid;
        this.coursename = coursename;
        this.courseidentifier = courseidentifier;
        this.instructor = instructor;
        this.scheduleblockid = scheduleblockid;
    }
    public Courses(int courseid, int schoolid, String instructor, int scheduleblockid) {
        this.courseid = courseid;
        this.schoolid = schoolid;
        this.instructor = instructor;
        this.scheduleblockid = scheduleblockid;
    }

    public Courses(int courseid, int schoolid, String coursename, String description, String courseidentifier, Integer numstudents, String instructor, int scheduleblockid) {
        this.courseid = courseid;
        this.schoolid = schoolid;
        this.coursename = coursename;
        this.description = description;
        this.courseidentifier = courseidentifier;
        this.numstudents = numstudents;
        this.instructor = instructor;
        this.scheduleblockid = scheduleblockid;
    }

    public int getCourseid() {
        return this.courseid;
    }

    public void setCourseid(int courseid) {
        this.courseid = courseid;
    }

    public int getSchoolid() {
        return this.schoolid;
    }

    public void setSchoolid(int schoolid) {
        this.schoolid = schoolid;
    }

    public String getCoursename() {
        return this.coursename;
    }

    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCourseidentifier() {
        return this.courseidentifier;
    }

    public void setCourseidentifier(String courseidentifier) {
        this.courseidentifier = courseidentifier;
    }

    public Integer getNumstudents() {
        return this.numstudents;
    }

    public void setNumstudents(Integer numstudents) {
        this.numstudents = numstudents;
    }

    public String getInstructor() {
        return this.instructor;
    }

    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }

    public int getScheduleblockid() {
        return this.scheduleblockid;
    }

    public void setScheduleblockid(int scheduleblockid) {
        this.scheduleblockid = scheduleblockid;
    }
    public void incrementStudents(){
        numstudents++;
    }
    public void decrementStudents(){
        numstudents--;
    }
}
