package Mapping.POJO;
// Generated Mar 7, 2015 9:53:12 AM by Hibernate Tools 4.3.1



/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private int courseid;
     private int schoolid;
     private String coursename;
     private String description;
     private String courseidentifier;
     private Integer numstudents;
     private String instructor;

    public Courses() {
    }

	
    public Courses(int courseid, int schoolid, String instructor) {
        this.courseid = courseid;
        this.schoolid = schoolid;
        this.instructor = instructor;
    }
    public Courses(int courseid, int schoolid, String coursename, String description, String courseidentifier, Integer numstudents, String instructor) {
       this.courseid = courseid;
       this.schoolid = schoolid;
       this.coursename = coursename;
       this.description = description;
       this.courseidentifier = courseidentifier;
       this.numstudents = numstudents;
       this.instructor = instructor;
    }
   
    public int getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(int courseid) {
        this.courseid = courseid;
    }
    public int getSchoolid() {
        return this.schoolid;
    }
    
    public void setSchoolid(int schoolid) {
        this.schoolid = schoolid;
    }
    public String getCoursename() {
        return this.coursename;
    }
    
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCourseidentifier() {
        return this.courseidentifier;
    }
    
    public void setCourseidentifier(String courseidentifier) {
        this.courseidentifier = courseidentifier;
    }
    public Integer getNumstudents() {
        return this.numstudents;
    }
    
    public void setNumstudents(Integer numstudents) {
        this.numstudents = numstudents;
    }
    public String getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(String instructor) {
        this.instructor = instructor;
    }




}


