package Mapping.POJO;
// Generated Mar 7, 2015 9:53:12 AM by Hibernate Tools 4.3.1



/**
 * FriendshipId generated by hbm2java
 */
public class FriendshipId  implements java.io.Serializable {


     private int requester;
     private int requestee;

    public FriendshipId() {
    }

    public FriendshipId(int requester, int requestee) {
       this.requester = requester;
       this.requestee = requestee;
    }
   
    public int getRequester() {
        return this.requester;
    }
    
    public void setRequester(int requester) {
        this.requester = requester;
    }
    public int getRequestee() {
        return this.requestee;
    }
    
    public void setRequestee(int requestee) {
        this.requestee = requestee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendshipId) ) return false;
		 FriendshipId castOther = ( FriendshipId ) other; 
         
		 return (this.getRequester()==castOther.getRequester())
 && (this.getRequestee()==castOther.getRequestee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRequester();
         result = 37 * result + this.getRequestee();
         return result;
   }   


}


