package Mapping.POJO;
// Generated Mar 7, 2015 9:53:12 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Friendship generated by hbm2java
 */
public class Friendship  implements java.io.Serializable {


     private FriendshipId id;
     private Boolean accepted;
     private Date date;

    public Friendship() {
    }

	
    public Friendship(FriendshipId id) {
        this.id = id;
    }
    public Friendship(FriendshipId id, Boolean accepted, Date date) {
       this.id = id;
       this.accepted = accepted;
       this.date = date;
    }
   
    public FriendshipId getId() {
        return this.id;
    }
    
    public void setId(FriendshipId id) {
        this.id = id;
    }
    public Boolean getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


