package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Friendships generated by hbm2java
 */
public class Friendships  implements java.io.Serializable {


     private FriendshipsId id;
     private Boolean accepted;
     private Date date;

    public Friendships() {
    }

	
    public Friendships(FriendshipsId id) {
        this.id = id;
    }
    public Friendships(FriendshipsId id, Boolean accepted, Date date) {
       this.id = id;
       this.accepted = accepted;
       this.date = date;
    }
   
    public FriendshipsId getId() {
        return this.id;
    }
    
    public void setId(FriendshipsId id) {
        this.id = id;
    }
    public Boolean getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


