package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1

/**
 * FriendshipsId generated by hbm2java
 */
public class FriendshipsId implements java.io.Serializable {

    private int friend2;
    private int friend1;

    public FriendshipsId() {
    }

    public FriendshipsId(int friend2, int friend1) {
        this.friend2 = friend2;
        this.friend1 = friend1;
    }

    public int getFriend2() {
        return this.friend2;
    }

    public void setFriend2(int friend2) {
        this.friend2 = friend2;
    }

    public int getFriend1() {
        return this.friend1;
    }

    public void setFriend1(int friend1) {
        this.friend1 = friend1;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof FriendshipsId)) {
            return false;
        }
        FriendshipsId castOther = (FriendshipsId) other;

        return (this.getFriend2() == castOther.getFriend2())
                && (this.getFriend1() == castOther.getFriend1());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getFriend2();
        result = 37 * result + this.getFriend1();
        return result;
    }

}
