package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1



/**
 * Generationcriteria generated by hbm2java
 */
public class Generationcriteria  implements java.io.Serializable {


     private Integer generationcriteriaid;
     private Integer studentid;
     private String courseids;
     private String lunch;

    public String getLunch() {
        return lunch;
    }

    public void setLunch(String lunch) {
        this.lunch = lunch;
    }

    public Generationcriteria() {
    }

    public Generationcriteria(Integer studentid, String courseids, String instructors) {
       this.studentid = studentid;
       this.courseids = courseids;

    }
   
    public Integer getGenerationcriteriaid() {
        return this.generationcriteriaid;
    }
    
    public void setGenerationcriteriaid(Integer generationcriteriaid) {
        this.generationcriteriaid = generationcriteriaid;
    }
    public Integer getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }
    public String getCourseids() {
        return this.courseids;
    }
    
    public void setCourseids(String courseids) {
        this.courseids = courseids;
    }




}


