package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1



/**
 * Generationcriteria generated by hbm2java
 */
public class Generationcriteria  implements java.io.Serializable {


     private Integer generationcriteriaid;
     private Integer studentid;
     private String courseidentifiers;
     private String instructors;

    public Generationcriteria() {
    }

    public Generationcriteria(Integer studentid, String courseidentifiers, String instructors) {
       this.studentid = studentid;
       this.courseidentifiers = courseidentifiers;
       this.instructors = instructors;
    }
   
    public Integer getGenerationcriteriaid() {
        return this.generationcriteriaid;
    }
    
    public void setGenerationcriteriaid(Integer generationcriteriaid) {
        this.generationcriteriaid = generationcriteriaid;
    }
    public Integer getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }
    public String getCourseidentifiers() {
        return this.courseidentifiers;
    }
    
    public void setCourseidentifiers(String courseidentifiers) {
        this.courseidentifiers = courseidentifiers;
    }
    public String getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(String instructors) {
        this.instructors = instructors;
    }




}


