package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1



/**
 * Registrations generated by hbm2java
 */
public class Registrations  implements java.io.Serializable {


     private RegistrationsId id;

    public Registrations() {
    }

    public Registrations(RegistrationsId id) {
       this.id = id;
    }
   
    public RegistrationsId getId() {
        return this.id;
    }
    
    public void setId(RegistrationsId id) {
        this.id = id;
    }




}


