package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1



/**
 * RegistrationsId generated by hbm2java
 */
public class RegistrationsId  implements java.io.Serializable {


     private int courseid;
     private int studentid;

    public RegistrationsId() {
    }

    public RegistrationsId(int courseid, int studentid) {
       this.courseid = courseid;
       this.studentid = studentid;
    }
   
    public int getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(int courseid) {
        this.courseid = courseid;
    }
    public int getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(int studentid) {
        this.studentid = studentid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistrationsId) ) return false;
		 RegistrationsId castOther = ( RegistrationsId ) other; 
         
		 return (this.getCourseid()==castOther.getCourseid())
 && (this.getStudentid()==castOther.getStudentid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCourseid();
         result = 37 * result + this.getStudentid();
         return result;
   }   


}


