package Mapping.POJO;
// Generated Mar 7, 2015 9:53:12 AM by Hibernate Tools 4.3.1



/**
 * Scheduleblock generated by hbm2java
 */
public class Scheduleblock  implements java.io.Serializable {


     private Integer scheduleblockid;
     private Integer schoolid;
     private Integer period;
     private String days;
     private String semester;

    public Scheduleblock() {
    }

    public Scheduleblock(Integer schoolid, Integer period, String days, String semester) {
       this.schoolid = schoolid;
       this.period = period;
       this.days = days;
       this.semester = semester;
    }
   
    public Integer getScheduleblockid() {
        return this.scheduleblockid;
    }
    
    public void setScheduleblockid(Integer scheduleblockid) {
        this.scheduleblockid = scheduleblockid;
    }
    public Integer getSchoolid() {
        return this.schoolid;
    }
    
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }
    public Integer getPeriod() {
        return this.period;
    }
    
    public void setPeriod(Integer period) {
        this.period = period;
    }
    public String getDays() {
        return this.days;
    }
    
    public void setDays(String days) {
        this.days = days;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }




}


