package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1



/**
 * Schools generated by hbm2java
 */
public class Schools  implements java.io.Serializable {


     private Integer schoolid;
     private String schoolname;
     private String academicyear;
     private Integer numstudents;
     private Integer numsemesters;
     private Integer numperiods;
     private Integer numdays;
     private String lunchrange;
     private String scheduleblocks;

    public Schools() {
    }

	
    public Schools(String schoolname, String academicyear) {
        this.schoolname = schoolname;
        this.academicyear = academicyear;
    }
    public Schools(String schoolname, String academicyear, Integer numstudents, Integer numsemesters, Integer numperiods, Integer numdays, String lunchrange, String scheduleblocks) {
       this.schoolname = schoolname;
       this.academicyear = academicyear;
       this.numstudents = numstudents;
       this.numsemesters = numsemesters;
       this.numperiods = numperiods;
       this.numdays = numdays;
       this.lunchrange = lunchrange;
       this.scheduleblocks = scheduleblocks;
    }
   
    public Integer getSchoolid() {
        return this.schoolid;
    }
    
    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }
    public String getSchoolname() {
        return this.schoolname;
    }
    
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname;
    }
    public String getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }
    public Integer getNumstudents() {
        return this.numstudents;
    }
    
    public void setNumstudents(Integer numstudents) {
        this.numstudents = numstudents;
    }
    public Integer getNumsemesters() {
        return this.numsemesters;
    }
    
    public void setNumsemesters(Integer numsemesters) {
        this.numsemesters = numsemesters;
    }
    public Integer getNumperiods() {
        return this.numperiods;
    }
    
    public void setNumperiods(Integer numperiods) {
        this.numperiods = numperiods;
    }
    public Integer getNumdays() {
        return this.numdays;
    }
    
    public void setNumdays(Integer numdays) {
        this.numdays = numdays;
    }
    public String getLunchrange() {
        return this.lunchrange;
    }
    
    public void setLunchrange(String lunchrange) {
        this.lunchrange = lunchrange;
    }
    public String getScheduleblocks() {
        return this.scheduleblocks;
    }
    
    public void setScheduleblocks(String scheduleblocks) {
        this.scheduleblocks = scheduleblocks;
    }




}


