package Mapping.POJO;
// Generated Mar 18, 2015 11:06:19 AM by Hibernate Tools 4.3.1

import java.util.List;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

    private Integer studentid;
    private String email;
    private String firstname;
    private String lastname;
    private String password;
    private Boolean loggedin;
    private Integer schoolid;
    private Boolean approved;
    private String role;
    private List<Courses> generatedschedule;

    public List<Courses> getGeneratedschedule() {
        return generatedschedule;
    }

    public void setGeneratedschedule(List<Courses> generatedschedule) {
        this.generatedschedule = generatedschedule;
    }

    public Students() {
    }

    public Students(String email, String firstname, String lastname, String role) {
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.role = role;
    }

    public Students(String email, String firstname, String lastname) {
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
    }

    public Students(String email, String firstname, String lastname, String password, Boolean loggedin, Integer schoolid, Boolean approved, String role) {
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.loggedin = loggedin;
        this.schoolid = schoolid;
        this.approved = approved;
        this.role = role;
    }

    public Integer getStudentid() {
        return this.studentid;
    }

    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getLoggedin() {
        return this.loggedin;
    }

    public void setLoggedin(Boolean loggedin) {
        this.loggedin = loggedin;
    }

    public Integer getSchoolid() {
        return this.schoolid;
    }

    public void setSchoolid(Integer schoolid) {
        this.schoolid = schoolid;
    }

    public Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

}
